---
- name: gather information from routers
  hosts: rtr2
  gather_facts: no

  tasks:
    - name: gather router facts
      eos_facts:

    - name: display version
      debug:
        msg: "The EOS version is: {{ ansible_net_version }}"

    - name: display serial number
      debug:
        msg: "The serial number is:{{ ansible_net_serialnum }}"

    - name: Persist serial number for subsequent playbooks executions
      set_stats:
        data:
          router_serialnum: "{{ ansible_net_serialnum }}"

    - name: DEBUG - output router_serialnum
      debug:
        var: router_serialnum
