---
- name: set router banners
  hosts: "{{ network_inventory_limit }}"
  gather_facts: no

  vars:
    network_inventory_limit: routers

  tasks:
    - name: load banner onto network device
      vars:
        - network_banner:  "{{ net_banner | default(None) }}"
        - banner_type: "{{ net_type | default('login') }}"
      include_role:
        name: banner
