---
- name: configure l3 interface on arista eos
  hosts: arista
  gather_facts: no

  tasks:
    - name: Merge provided configuration with device configuration.
      arista.eos.eos_l3_interfaces:
      config:
      - name: "{{ interface_name }}"
        ipv4:
        - address: "{{ interface_ipv4 }}"
      state: merged
